import { apiFetch, API_BASE_URL } from './client';
import type { AppLanguage } from '../../i18n';

/**
 * One possible condition.
 *
 * `code` is the stable, canonical identifier the backend groups and counts on.
 * It is deliberately NOT translated. `displayName` is the patient-facing label,
 * generated by the AI in the language the patient selected. `name` is retained
 * as a legacy alias for responses cached before this change.
 */
export interface AgentCondition {
  code: string;
  displayName: string;
  name?: string;
  confidencePercent: number;
}

/** Real, configured pricing only. Never derived from the language model. */
export interface AgentCostEstimate {
  currency: 'TZS';
  isEstimate: true;
  low: number;
  high: number;
}

/** A real facility resolved by the location service, with a real route. */
export interface AgentHospital {
  id?: string;
  name: string;
  distanceKm?: number;
  estimatedTravelMinutes?: number;
  latitude?: number;
  longitude?: number;
  mapUrl?: string;
}

export interface AgentChatReply {
  status?: 'ok' | 'model_unavailable';
  reply: string;
  /** Language the reply was actually generated in. */
  language?: AppLanguage;
  possibleConditions?: AgentCondition[];
  costEstimate?: AgentCostEstimate;
  hospital?: AgentHospital;
  actions?: Array<'show_conditions' | 'find_hospital' | 'show_map' | 'review_case' | 'send_case' | 'book_appointment' | 'rate_service'>;
  /** Server asks for a 1-5 service rating at the end of the journey. */
  askFeedback?: boolean;
  disclaimer?: string;
}

export async function sendAgentMessage(
  message: string,
  caseId?: string | null,
  attachmentId?: string | null,
  /**
   * The patient's selected app language. AI-generated prose cannot be localized
   * by translation keys, so the backend prompt needs this in order to answer in
   * the right language.
   */
  language?: AppLanguage,
): Promise<AgentChatReply> {
  const response = await apiFetch<{ data: AgentChatReply }>('/agent/chat', {
    method: 'POST',
    body: JSON.stringify({
      message,
      caseId: caseId ?? undefined,
      attachmentId: attachmentId ?? undefined,
      language: language ?? undefined,
    }),
  });
  return response.data;
}

/** The patient's own 1-5 rating of the service they received. */
export async function submitAgentFeedback(
  rating: number,
  caseId?: string | null,
  language?: AppLanguage,
  comment?: string,
): Promise<void> {
  await apiFetch('/agent/feedback', {
    method: 'POST',
    body: JSON.stringify({ rating, caseId: caseId ?? undefined, language, comment }),
  });
}

/** One persisted turn in the patient's own agent transcript. */
export interface StoredAgentMessage {
  id: string;
  caseId: string | null;
  role: 'patient' | 'assistant';
  text: string | null;
  createdAt: string | null;
  attachment?: {
    id: string;
    filename: string;
    contentType: string;
    sizeBytes: number;
    kind: string;
  };
}

/**
 * The authenticated patient's own transcript, oldest first.
 *
 * This is server-side state keyed to the account, so signing out and back in
 * restores the same history and another patient can never see it.
 */
export async function fetchAgentHistory(): Promise<StoredAgentMessage[]> {
  const response = await apiFetch<{ data: StoredAgentMessage[] }>('/agent/history');
  return response.data ?? [];
}

/** Absolute URL for downloading a stored attachment. */
export function attachmentUrl(id: string): string {
  return `${API_BASE_URL}/agent/attachments/${id}`;
}

export default sendAgentMessage;
